name: Deploy to VPS

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Sync source to VPS
        run: |
          rsync -az --delete --exclude target ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

      - name: Build and restart service
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
            set -e
            cd '"$DEPLOY_PATH"' &&
            source $HOME/.cargo/env ||
            (curl -fsSL https://sh.rustup.rs | sh -s -- -y && source $HOME/.cargo/env)
            cargo build --release --locked
            sudo systemctl restart '"$SERVICE_NAME"'
          '
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
